---
- name: Install packages
  hosts: STAGING
  become: yes

  tasks:
  - name: Install Net tools
    apt: name=net-tools state=latest

  - name: Install Storage tools
    apt: name=ncdu state=latest

  - name: Install ZSH command line
    apt: name=zsh state=latest

  - name: Install Wget util
    apt: name=wget state=latest

  - name: Install VIM editor
    apt: name=vim state=latest

  - name: Install NGINX Web Server
    apt: name=nginx state=latest

  - name: Start NGINX
    service: name=nginx state=started

  - name: Install Docker
    apt: name=docker state=latest
