---
- name: Setup environment
  hosts: STAGING
  become: yes

  tasks:
  - name: Install packages
    apt:
      pkg:
      - net-tools
      - ncdu
      - zsh
      - wget
      - vim
      - nginx
      - docker
      update_cache: yes

  - name: Start NGINX
    service:
      name: nginx
      state: started
