---
- name: Setup environment
  hosts: "{{ target }}"
  become: yes

  tasks:
  - name: Install packages
    apt:
      pkg:
      - net-tools
      - ncdu
      - htop
      - zsh
      - wget
      - vim
      - nginx
      - docker
      - certbot
      update_cache: yes

  - name: Setup cron for autoupdate letsencrypt
    cron:
      name: Autoupdate Let's Encrypt certificate
      minute: "42"
      hour: "0,12"
      job: letsencrypt renew --post-hook "service nginx reload"

  - name: Start NGINX
    service:
      name: nginx
      state: started
