---
- name: Setup environment
  hosts: "{{ target }}"
  become: true

  tasks:
  - name: Install packages
    import_tasks: packages.yml

  - name: Start NGINX
    service:
      name: nginx
      state: started
