---
- name: Setup environment
  hosts: "TAPETOWN"
  become: true

  tasks:
  - name: Install packages
    import_tasks: packages.yml

  - name: Let's encrypt certs update
    import_tasks: letsencrypt.yml

  - name: Fetch nginx configs from git
    git:
      repo: https://github.com/tapetown/website.git
      dest: /usr/local/website
      update: yes
      version: main

  - name: Replace nginx configuration
    shell: cp /usr/local/website/tapetown.conf /etc/nginx/conf.d/

  - name: Reload nginx
    service:
      name: nginx
      state: reloaded
