---
- name: Update
  hosts: "TAPETOWN"
  become: true

  tasks:
  - name: Install packages
    import_tasks: packages.yml

  - name: Fetch tapetown
    git:
      repo: https://github.com/tapetown/website.git
      dest: /usr/local/website
      update: yes
      version: main

  - name: Update nginx
    shell: cp /usr/local/website/tapetown.conf /etc/nginx/conf.d/

  - name: Stop nginx
    shell: kill $(ps aux | grep '[n]ginx' | awk '{print $2}')

  - name: Start nginx
    service:
      name: nginx
      state: started
