- name: Update nginx
  hosts: "TAPETOWN"
  become: true

  tasks:
  - name: Update nginx
    shell: cp /usr/local/website/tapetown.conf /etc/nginx/conf.d/

  - name: Stop nginx
    shell: kill $(ps aux | grep '[n]ginx' | awk '{print $2}')

  - name: Start nginx
    service:
      name: nginx
      state: started